# Generated by Django 5.1.6 on 2025-06-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantmanager',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='VerificationCode',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=None, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='firstName',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='lastName',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.DeleteModel(
            name='RestaurantManager',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
