# Generated by Django 5.1.6 on 2025-06-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=25)),
                ('isVerified', models.BooleanField(default=False)),
                ('restaurantName', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
