# Generated by Django 5.1.6 on 2025-06-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('sendDate', models.DateTimeField(auto_now_add=True)),
                ('forLogin', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
